name: Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      DOCKER_REGISTRY: "ghcr.io/omec-project/"
      DOCKER_REPOSITORY: "upf-epc/"
    runs-on: ubuntu-latest
    steps:
    # Checkout and build
    - uses: actions/checkout@v2.3.2
    - name: Docker login GH packages
      env:
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo $PASSWORD | docker login ghcr.io -u USERNAME --password-stdin
    - name: Build and push Docker image
      run: |
        make docker-build
        make docker-push
