name: Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      DOCKER_REGISTRY: "ghcr.io/omec-project/"
      DOCKER_REPOSITORY: ""
    runs-on: ubuntu-latest
    steps:
    # Checkout and build
    - uses: actions/checkout@v2.3.3
    - name: Docker login GH packages
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u krsna1729 --password-stdin
    - name: Build and push Docker image
      run: |
        make docker-build
        make docker-push
